OSError: Cannot understand given URI: array([[   0,    0,    0,    0,    0,    0,    0,    0,  ....
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
c:\Users\Rivers\Desktop\FUESMEN\Trabajo riñones\main.py in <module>
     98 #Ejecuta función main()
     99 if __name__ == '__main__':
--> 100     main()

c:\Users\Rivers\Desktop\FUESMEN\Trabajo riñones\main.py in main()
     75 
     76                 # MASCARA
---> 77                 image = skimage.io.imread(fname=Data_img)
     78                 skimage.io.imshow(image)
     79 

~\Anaconda3\lib\site-packages\skimage\io\_io.py in imread(fname, as_gray, plugin, **plugin_args)
     46 
     47     with file_or_url_context(fname) as fname:
---> 48         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     49 
     50     if not hasattr(img, 'ndim'):

~\Anaconda3\lib\site-packages\skimage\io\manage_plugins.py in call_plugin(kind, *args, **kwargs)
    205                                (plugin, kind))
    206 
--> 207     return func(*args, **kwargs)
    208 
    209 

~\Anaconda3\lib\site-packages\skimage\io\_plugins\imageio_plugin.py in imread(*args, **kwargs)
      8 @wraps(imageio_imread)
      9 def imread(*args, **kwargs):
---> 10     return np.asarray(imageio_imread(*args, **kwargs))

~\Anaconda3\lib\site-packages\imageio\core\functions.py in imread(uri, format, **kwargs)
    263 
    264     # Get reader and read first
--> 265     reader = read(uri, format, "i", **kwargs)
    266     with reader:
    267         return reader.get_data(0)

~\Anaconda3\lib\site-packages\imageio\core\functions.py in get_reader(uri, format, mode, **kwargs)
    170 
    171     # Create request object
--> 172     request = Request(uri, "r" + mode, **kwargs)
    173 
    174     # Get format

~\Anaconda3\lib\site-packages\imageio\core\request.py in __init__(self, uri, mode, **kwargs)
    122 
    123         # Parse what was given
--> 124         self._parse_uri(uri)
    125 
    126         # Set extension

~\Anaconda3\lib\site-packages\imageio\core\request.py in _parse_uri(self, uri)
    220             if len(uri_r) > 60:
    221                 uri_r = uri_r[:57] + "..."
--> 222             raise IOError("Cannot understand given URI: %s." % uri_r)
    223 
    224         # Check if this is supported

OSError: Cannot understand given URI: array([[   0,    0,    0,    0,    0,    0,    0,    0,  ....
